name: Self Tests

on: [push]

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.8.9'
#           architecture: 'x64'
      - name: Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Python 3.8
        run: |
          brew install python@3.8
          echo "/usr/local/opt/python@3.8/bin" >> $GITHUB_PATH
      - name: Update Pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Dependencies
        run: |
          make environment
      - name: Install Modules
        run: |
          make install validate
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          export PYTHONUNBUFFERED=1
          make coverage

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.9'
        architecture: 'x64'
    - name: Install Dependencies
      run: |
        sudo apt-get install libgmp-dev
        sudo apt-get install libmpfr-dev
        sudo apt-get install libmpc-dev
        python -m pip install --upgrade pip
        make environment
    - name: Install Modules
      run: |
        make install validate
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        export PYTHONUNBUFFERED=1
        make coverage